import { jsPDF } from "jspdf";

export interface IntelligenceReport {
  id: string;
  title: string;
  author: string;
  date: string;
  pages?: number;
  classification?: string;
  summary: string;
  intelligenceOverview?: string;
  findings: string[];
  entityRelationships?: Array<{
    source: string;
    target: string;
    type: string;
    detail: string;
  }>;
  riskLevel?: "CRITICAL" | "HIGH" | "MODERATE" | "LOW" | string;
  riskAssessment?: {
    level: string;
    score: number;
    factors: string[];
  };
  entities?: string[];
  analystNotes?: string;
  recommendations: string[];
  generatedBy?: string;
}

/**
 * Generates an official Cyber Cell Intelligence Brief PDF Dossier
 * and triggers an automatic browser download.
 */
export async function generateReportPDF(report: IntelligenceReport): Promise<void> {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const classification = report.classification || "OFFICIAL S-4";
  const timestamp = new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";

  // Helper to check page bounds
  const checkPageBreak = (neededHeight: number) => {
    if (y + neededHeight > pageHeight - 20) {
      doc.addPage();
      y = margin;
      drawWatermark();
      drawHeader();
    }
  };

  // Helper for watermark
  const drawWatermark = () => {
    doc.saveGraphicsState();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(42);
    doc.setTextColor(230, 235, 240);
    // Draw rotated watermark in center
    doc.text("NETRAGRAPH AI // " + classification, pageWidth / 2, pageHeight / 2, {
      align: "center",
      angle: 45,
    });
    doc.restoreGraphicsState();
  };

  // Helper for Top Running Header
  const drawHeader = () => {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(100, 116, 139);
    doc.text("NETRAGRAPH AI · INTELLIGENCE OPERATIONS CONSOLE", margin, 10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(180, 83, 9);
    doc.text(`[ ${classification} ]`, pageWidth - margin, 10, { align: "right" });
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, 12, pageWidth - margin, 12);
  };

  // Helper for Bottom Footer
  const drawFooters = () => {
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.3);
      doc.line(margin, pageHeight - 12, pageWidth - margin, pageHeight - 12);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(100, 116, 139);
      doc.text(
        "Generated by NetraGraph AI Intelligence System · Official Secrets Act §5 & IT Act §69B",
        margin,
        pageHeight - 8
      );
      doc.text(
        `Page ${i} of ${totalPages} · ${report.id}`,
        pageWidth - margin,
        pageHeight - 8,
        { align: "right" }
      );
    }
  };

  // 1. Initial Page Setup
  drawWatermark();
  drawHeader();
  y = 20;

  // 2. Report Document Title Banner
  doc.setFillColor(15, 23, 42); // Slate-900 dark header box
  doc.roundedRect(margin, y, contentWidth, 26, 1.5, 1.5, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text(report.title.toUpperCase(), margin + 5, y + 9);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(148, 163, 184);
  doc.text("CRIMINAL INTELLIGENCE ANALYSIS SYSTEM · INVESTIGATION DOSSIER", margin + 5, y + 15);

  doc.setFont("courier", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(56, 189, 248);
  doc.text(`REPORT REF: ${report.id}`, margin + 5, y + 21);

  doc.setFont("helvetica", "bold");
  doc.setTextColor(251, 146, 60);
  doc.text(`CLASSIFICATION: ${classification}`, pageWidth - margin - 5, y + 21, { align: "right" });

  y += 32;

  // 3. Metadata Key-Value Grid
  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.roundedRect(margin, y, contentWidth, 18, 1, 1, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(71, 85, 105);

  doc.text("AUTHOR / LEAD:", margin + 4, y + 6);
  doc.text("DATE OF RECORD:", margin + 50, y + 6);
  doc.text("GENERATED TIMESTAMP:", margin + 95, y + 6);
  doc.text("THREAT LEVEL:", margin + 145, y + 6);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(15, 23, 42);

  doc.text(report.author || "Insp. D. Bose", margin + 4, y + 12);
  doc.text(report.date || "2026-08-26", margin + 50, y + 12);
  doc.setFont("courier", "normal");
  doc.text(timestamp.slice(0, 16), margin + 95, y + 12);
  doc.setFont("helvetica", "bold");
  const rLvl = report.riskLevel || report.riskAssessment?.level || "HIGH";
  if (rLvl.includes("CRITICAL")) doc.setTextColor(220, 38, 38);
  else if (rLvl.includes("HIGH")) doc.setTextColor(217, 119, 6);
  else doc.setTextColor(37, 99, 235);
  doc.text(rLvl, margin + 145, y + 12);

  y += 24;

  // Helper function to render a section
  const renderSectionHeader = (title: string, count?: number) => {
    checkPageBreak(12);
    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, y, contentWidth, 6.5, 0.5, 0.5, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(9);
    doc.setTextColor(30, 41, 59);
    doc.text(title.toUpperCase(), margin + 3, y + 4.5);

    if (count !== undefined) {
      doc.setFont("courier", "bold");
      doc.setFontSize(8);
      doc.setTextColor(71, 85, 105);
      doc.text(`[ ${count} ITEMS ]`, pageWidth - margin - 3, y + 4.5, { align: "right" });
    }

    y += 9;
  };

  // 4. Section 1: Executive Summary
  renderSectionHeader("1. Executive Summary");
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(51, 65, 85);
  const summaryLines = doc.splitTextToSize(report.summary, contentWidth - 4);
  doc.text(summaryLines, margin + 2, y);
  y += summaryLines.length * 4.2 + 4;

  // 5. Section 2: Intelligence Overview
  if (report.intelligenceOverview) {
    renderSectionHeader("2. Intelligence Overview & Tactical Context");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(51, 65, 85);
    const overviewLines = doc.splitTextToSize(report.intelligenceOverview, contentWidth - 4);
    doc.text(overviewLines, margin + 2, y);
    y += overviewLines.length * 4.2 + 4;
  }

  // 6. Section 3: Key Findings
  if (report.findings && report.findings.length > 0) {
    renderSectionHeader("3. Key Investigatory Findings", report.findings.length);
    report.findings.forEach((finding, idx) => {
      checkPageBreak(10);
      doc.setFillColor(248, 250, 252);
      doc.setDrawColor(226, 232, 240);
      doc.setLineWidth(0.2);
      doc.roundedRect(margin, y, contentWidth, 7, 0.5, 0.5, "FD");

      doc.setFont("courier", "bold");
      doc.setFontSize(8);
      doc.setTextColor(37, 99, 235);
      doc.text(`[FINDING 0${idx + 1}]`, margin + 3, y + 4.8);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      const textLines = doc.splitTextToSize(finding, contentWidth - 36);
      doc.text(textLines, margin + 30, y + 4.8);

      y += Math.max(7, textLines.length * 4.2 + 2) + 2;
    });
    y += 2;
  }

  // 7. Section 4: Entity Relationships
  if (report.entityRelationships && report.entityRelationships.length > 0) {
    renderSectionHeader("4. Entity Relationships & Link Analysis", report.entityRelationships.length);
    report.entityRelationships.forEach((rel) => {
      checkPageBreak(8);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      doc.text(`• ${rel.source}`, margin + 3, y + 3.5);

      doc.setFont("courier", "bold");
      doc.setFontSize(8);
      doc.setTextColor(217, 119, 6);
      doc.text(` --[ ${rel.type} ]--> `, margin + 45, y + 3.5);

      doc.setFont("helvetica", "bold");
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      doc.text(rel.target, margin + 85, y + 3.5);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(`(${rel.detail})`, margin + 125, y + 3.5);

      y += 6;
    });
    y += 3;
  } else if (report.entities && report.entities.length > 0) {
    renderSectionHeader("4. Indexed Associated Entities", report.entities.length);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8.5);
    doc.setTextColor(51, 65, 85);
    doc.text(`Target Entities Flagged: ${report.entities.join("  ·  ")}`, margin + 2, y + 2);
    y += 8;
  }

  // 8. Section 5: Risk Assessment
  renderSectionHeader("5. Threat Severity & Risk Assessment");
  const riskScore = report.riskAssessment?.score ?? (report.riskLevel === "CRITICAL" ? 92 : 78);
  const riskFactors = report.riskAssessment?.factors || [
    "Cross-border financial routing detected",
    "High betweenness centrality bridge node",
    "Multiple burner MSISDN call linkages",
  ];

  doc.setFillColor(248, 250, 252);
  doc.setDrawColor(226, 232, 240);
  doc.setLineWidth(0.3);
  doc.roundedRect(margin, y, contentWidth, 16, 1, 1, "FD");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(8.5);
  doc.setTextColor(71, 85, 105);
  doc.text("AGGREGATE THREAT SCORE:", margin + 4, y + 6);
  doc.text("RISK DRIVERS:", margin + 65, y + 6);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(220, 38, 38);
  doc.text(`${riskScore}/100`, margin + 4, y + 12);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(51, 65, 85);
  doc.text(riskFactors.slice(0, 2).join("; "), margin + 65, y + 11);

  y += 21;

  // 9. Section 6: Analyst Notes
  if (report.analystNotes) {
    renderSectionHeader("6. Operational Analyst Notes");
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8.5);
    doc.setTextColor(51, 65, 85);
    const noteLines = doc.splitTextToSize(report.analystNotes, contentWidth - 4);
    doc.text(noteLines, margin + 2, y);
    y += noteLines.length * 4.2 + 4;
  }

  // 10. Section 7: Recommendations
  if (report.recommendations && report.recommendations.length > 0) {
    renderSectionHeader("7. Strategic Recommendations & Action Directives", report.recommendations.length);
    report.recommendations.forEach((rec, idx) => {
      checkPageBreak(8);
      doc.setFont("courier", "bold");
      doc.setFontSize(8);
      doc.setTextColor(22, 163, 74);
      doc.text(`[ACTION ${idx + 1}]`, margin + 2, y + 3.5);

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8.5);
      doc.setTextColor(15, 23, 42);
      const recLines = doc.splitTextToSize(rec, contentWidth - 26);
      doc.text(recLines, margin + 22, y + 3.5);

      y += Math.max(6, recLines.length * 4.2 + 1) + 1.5;
    });
  }

  // 11. Finalize Footers on All Pages
  drawFooters();

  // 12. Trigger Browser Download
  const filename = `${report.id}_${report.title.toLowerCase().replace(/[^a-z0-9]/g, "_")}_dossier.pdf`;
  doc.save(filename);
}
