"""Operational service orchestrating emerging threat detection and event lifecycle."""
from __future__ import annotations

import logging
import time
from typing import Any, Dict, List, Optional
from fastapi import HTTPException

from .bursts import TemporalBurstDetector
from .centrality import CentralityEvolutionDetector
from .community import CommunityEvolutionDetector
from .config import EmergingThreatConfig, EventLifecycleState, EventSeverity
from .events import EmergingThreatEvent, GOVERNANCE_DISCLAIMER, compute_event_fingerprint
from .explainability import EarlyWarningExplainabilityEngine
from .scoring import EarlyWarningScorer
from .snapshots import GraphSnapshot, TemporalSnapshotSequence
from .subgraphs import EmergingSubgraphDetector
from .topology import TopologyEvolutionDetector
from .trajectories import RiskTrajectoryAnalyzer

logger = logging.getLogger("EmergingThreatService")

# Prometheus Metrics Instrumentation
try:
    from prometheus_client import Counter, Histogram
    EMERGING_THREAT_REQUESTS_TOTAL = Counter(
        "netragraph_emerging_threat_requests_total",
        "Total emerging threat detection requests processed",
        ["status"],
    )
    EMERGING_THREAT_FAILURES_TOTAL = Counter(
        "netragraph_emerging_threat_failures_total",
        "Total emerging threat processing failures",
        ["reason"],
    )
    EMERGING_THREAT_DURATION_SECONDS = Histogram(
        "netragraph_emerging_threat_duration_seconds",
        "Emerging threat analysis latency in seconds",
        buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5],
    )
    EMERGING_THREAT_EVENTS_TOTAL = Counter(
        "netragraph_emerging_threat_events_total",
        "Total early-warning events generated by severity tier",
        ["severity"],
    )
    METRICS_AVAILABLE = True
except Exception:
    METRICS_AVAILABLE = False


class EmergingThreatService:
    """Singleton service for detecting emerging threat patterns and managing early-warning events."""

    _instance: Optional[EmergingThreatService] = None

    def __init__(self, config: Optional[EmergingThreatConfig] = None):
        self.config = config or EmergingThreatConfig()
        self.topology_detector = TopologyEvolutionDetector(self.config.topology)
        self.trajectory_analyzer = RiskTrajectoryAnalyzer(self.config.trajectory)
        self.centrality_detector = CentralityEvolutionDetector(self.config.centrality)
        self.community_detector = CommunityEvolutionDetector(self.config.community)
        self.burst_detector = TemporalBurstDetector(self.config.burst)
        self.subgraph_detector = EmergingSubgraphDetector()
        self.scorer = EarlyWarningScorer(self.config)
        self.explainability_engine = EarlyWarningExplainabilityEngine()

        # In-memory event registry with deduplication index
        self._events_by_id: Dict[str, EmergingThreatEvent] = {}
        self._fingerprint_to_id: Dict[str, str] = {}

    @classmethod
    def get_instance(cls) -> EmergingThreatService:
        if cls._instance is None:
            cls._instance = cls()
        return cls._instance

    def validate_safety_limits(self, sequence: TemporalSnapshotSequence) -> None:
        """Guards against pathological or denial-of-service analytical payloads."""
        limits = self.config.safety_limits
        if sequence.count > limits.max_snapshots:
            if METRICS_AVAILABLE:
                EMERGING_THREAT_FAILURES_TOTAL.labels(reason="too_many_snapshots").inc()
            raise HTTPException(
                status_code=413,
                detail=f"Request contains {sequence.count} snapshots, exceeding limit of {limits.max_snapshots}.",
            )

        for s in sequence.snapshots:
            if s.node_count > limits.max_nodes_per_snapshot:
                if METRICS_AVAILABLE:
                    EMERGING_THREAT_FAILURES_TOTAL.labels(reason="too_many_nodes").inc()
                raise HTTPException(
                    status_code=413,
                    detail=f"Snapshot contains {s.node_count} nodes, exceeding limit of {limits.max_nodes_per_snapshot}.",
                )
            if s.edge_count > limits.max_edges_per_snapshot:
                if METRICS_AVAILABLE:
                    EMERGING_THREAT_FAILURES_TOTAL.labels(reason="too_many_edges").inc()
                raise HTTPException(
                    status_code=413,
                    detail=f"Snapshot contains {s.edge_count} edges, exceeding limit of {limits.max_edges_per_snapshot}.",
                )

    def analyze_network_sequence(
        self,
        network_id: str,
        sequence: TemporalSnapshotSequence,
        external_dt_gnn_score: Optional[float] = None,
        external_fusion_score: Optional[float] = None,
    ) -> EmergingThreatEvent:
        """Executes full emerging-threat evaluation across a temporal graph snapshot sequence."""
        start_time = time.time()
        self.validate_safety_limits(sequence)

        try:
            if sequence.is_empty():
                # Safe empty baseline event
                fp = compute_event_fingerprint(network_id, [], 0.0, 0.0, "BASELINE_STABLE")
                return EmergingThreatEvent(
                    event_fingerprint=fp,
                    network_id=network_id,
                    entity_ids=[],
                    early_warning_score=0.0,
                    confidence_score=0.0,
                    severity=EventSeverity.LOW.value,
                    explanation={"summary_narrative": "No snapshot data available to evaluate emerging threats."},
                )

            snapshots = sequence.snapshots
            window_start = snapshots[0].timestamp
            window_end = snapshots[-1].timestamp
            window_duration = max(0.0, window_end - window_start)

            # 1. Topology evolution
            topo_metrics = None
            if len(snapshots) >= 2:
                topo_metrics = self.topology_detector.compare_snapshots(
                    snapshots[-2], snapshots[-1], max(0.001, window_end - snapshots[-2].timestamp)
                )
            topo_vel_score = topo_metrics.topology_velocity_score if topo_metrics else 0.0

            # 2. Trajectory analysis across snapshots
            # Extract aggregate or target risk scores across snapshots
            obs_series = []
            for s in snapshots:
                # Use snapshot fusion risk or average node risk
                if s.fusion_risk_score is not None:
                    obs_series.append((s.timestamp, s.fusion_risk_score))
                elif s.nodes:
                    valid_risks = [n.risk_score for n in s.nodes.values() if n.risk_score is not None]
                    avg_r = sum(valid_risks) / len(valid_risks) if valid_risks else 0.0
                    obs_series.append((s.timestamp, avg_r))
                else:
                    obs_series.append((s.timestamp, 0.0))

            traj_result = self.trajectory_analyzer.analyze_trajectory(network_id, obs_series)

            # 3. Centrality shifts
            centrality_shifts = {}
            if len(snapshots) >= 2:
                centrality_shifts = self.centrality_detector.compare_centralities(snapshots[-2], snapshots[-1])
            max_cent_vel = max((cs.centrality_velocity_score for cs in centrality_shifts.values()), default=0.0)

            # 4. Community evolution
            comm_metrics = None
            if len(snapshots) >= 2:
                comm_metrics = self.community_detector.compare_communities(snapshots[-2], snapshots[-1])
            comm_score = comm_metrics.community_evolution_score if comm_metrics else 0.0

            # 5. Temporal bursts
            burst_result = self.burst_detector.analyze_bursts(network_id, snapshots)

            # 6. Candidate emerging subgraphs
            subgraphs = self.subgraph_detector.extract_candidate_subgraphs(snapshots[-1])

            # Ingest external DT-GNN or Threat Fusion scores if provided
            dt_gnn_score = external_dt_gnn_score
            if dt_gnn_score is None and snapshots[-1].dt_gnn_anomaly_score is not None:
                dt_gnn_score = snapshots[-1].dt_gnn_anomaly_score

            fusion_score = external_fusion_score
            if fusion_score is None and snapshots[-1].fusion_risk_score is not None:
                fusion_score = snapshots[-1].fusion_risk_score

            # 7. Synthesize multi-signal early warning score
            scoring_res = self.scorer.calculate_score(
                trajectory_score=traj_result.trajectory_score,
                topology_velocity_score=topo_vel_score,
                centrality_velocity_score=max_cent_vel,
                temporal_burst_score=burst_result.burst_score,
                community_evolution_score=comm_score,
                dt_gnn_anomaly_score=dt_gnn_score,
                fusion_risk_score=fusion_score,
                snapshot_count=len(snapshots),
                timespan_seconds=window_duration,
            )

            ew_score = scoring_res["early_warning_score"]
            conf_score = scoring_res["confidence_score"]
            sev_str = scoring_res["severity"].value
            contributions = scoring_res["contributions"]

            # Classify overall event type
            if traj_result.trajectory_type in ["RAPID_ESCALATION", "SUDDEN_SPIKE"]:
                event_type = f"RISK_{traj_result.trajectory_type.value}"
            elif burst_result.burst_detected:
                event_type = "TEMPORAL_BURST_SURGE"
            elif topo_metrics and topo_metrics.anomalous_expansion_detected:
                event_type = "RAPID_TOPOLOGY_EXPANSION"
            elif any(cs.is_emerging_bridge for cs in centrality_shifts.values()):
                event_type = "BRIDGE_BROKER_EMERGENCE"
            else:
                event_type = "MULTI_SIGNAL_ACCELERATION"

            all_entities = sorted(list(snapshots[-1].node_ids()))

            # 8. Deterministic event fingerprinting for deduplication
            fingerprint = compute_event_fingerprint(
                network_id=network_id,
                entity_ids=all_entities,
                window_start=window_start,
                window_end=window_end,
                event_type=event_type,
            )

            # Check for deduplication
            if fingerprint in self._fingerprint_to_id:
                existing_id = self._fingerprint_to_id[fingerprint]
                existing_event = self._events_by_id.get(existing_id)
                if existing_event:
                    return existing_event

            # 9. Build structured explainability
            explanation = self.explainability_engine.generate_explanation(
                network_id=network_id,
                early_warning_score=ew_score,
                confidence_score=conf_score,
                severity=sev_str,
                contributions=contributions,
                trajectory_info={
                    "trajectory_type": traj_result.trajectory_type.value,
                    "trajectory_score": traj_result.trajectory_score,
                    "velocity": traj_result.velocity,
                    "narrative": traj_result.narrative,
                },
                topology_info={
                    "topology_velocity_score": topo_vel_score,
                    "narrative": topo_metrics.narrative if topo_metrics else "Stable",
                },
                burst_info={
                    "burst_detected": burst_result.burst_detected,
                    "burst_score": burst_result.burst_score,
                    "narrative": burst_result.narrative,
                },
                community_info={
                    "community_evolution_score": comm_score,
                    "narrative": comm_metrics.narrative if comm_metrics else "Stable",
                },
                subgraph_candidates=[
                    {
                        "subgraph_id": sg.subgraph_id,
                        "node_ids": sg.node_ids,
                        "edge_count": sg.edge_count,
                        "convergence_score": sg.convergence_score,
                        "narrative": sg.narrative,
                    }
                    for sg in subgraphs
                ],
                dt_gnn_signals={"score": dt_gnn_score} if dt_gnn_score is not None else {},
                fusion_signals={"score": fusion_score} if fusion_score is not None else {},
            )

            # 10. Assemble and register event
            event = EmergingThreatEvent(
                event_fingerprint=fingerprint,
                network_id=network_id,
                entity_ids=all_entities,
                observation_window={
                    "start": window_start,
                    "end": window_end,
                    "duration_seconds": window_duration,
                },
                event_type=event_type,
                early_warning_score=ew_score,
                confidence_score=conf_score,
                severity=sev_str,
                lifecycle_state=EventLifecycleState.DETECTED.value,
                trajectory={
                    "type": traj_result.trajectory_type.value,
                    "score": traj_result.trajectory_score,
                    "velocity": traj_result.velocity,
                    "acceleration": traj_result.acceleration,
                },
                topology_changes={
                    "node_growth_rate": topo_metrics.node_growth_rate if topo_metrics else 0.0,
                    "edge_growth_rate": topo_metrics.edge_growth_rate if topo_metrics else 0.0,
                    "node_churn": topo_metrics.node_churn if topo_metrics else 0.0,
                    "edge_churn": topo_metrics.edge_churn if topo_metrics else 0.0,
                    "velocity_score": topo_vel_score,
                },
                centrality_changes={
                    "max_velocity": max_cent_vel,
                    "bridges_detected": [cs.entity_id for cs in centrality_shifts.values() if cs.is_emerging_bridge],
                },
                community_changes={
                    "new_communities": comm_metrics.new_communities_formed if comm_metrics else 0,
                    "mergers": comm_metrics.communities_merged if comm_metrics else 0,
                    "fragmentations": comm_metrics.communities_fragmented if comm_metrics else 0,
                },
                temporal_bursts={
                    "burst_detected": burst_result.burst_detected,
                    "burst_score": burst_result.burst_score,
                    "max_events": burst_result.max_event_count_in_window,
                },
                subgraph_candidates=[
                    {
                        "subgraph_id": sg.subgraph_id,
                        "node_ids": sg.node_ids,
                        "edge_count": sg.edge_count,
                        "convergence_score": sg.convergence_score,
                        "label": sg.label,
                    }
                    for sg in subgraphs
                ],
                dt_gnn_signals={"score": dt_gnn_score, "anomaly_score": dt_gnn_score} if dt_gnn_score is not None else {},
                fusion_signals={"score": fusion_score, "fusion_score": fusion_score} if fusion_score is not None else {},
                explanation=explanation,
                disclaimer=GOVERNANCE_DISCLAIMER,
            )

            # Store in registry
            self._events_by_id[event.event_id] = event
            self._fingerprint_to_id[fingerprint] = event.event_id

            duration = time.time() - start_time
            if METRICS_AVAILABLE:
                EMERGING_THREAT_REQUESTS_TOTAL.labels(status="success").inc()
                EMERGING_THREAT_DURATION_SECONDS.observe(duration)
                EMERGING_THREAT_EVENTS_TOTAL.labels(severity=sev_str).inc()

            return event

        except HTTPException:
            raise
        except Exception as exc:
            logger.error(f"Error evaluating emerging threat for network {network_id}: {exc}")
            if METRICS_AVAILABLE:
                EMERGING_THREAT_REQUESTS_TOTAL.labels(status="error").inc()
                EMERGING_THREAT_FAILURES_TOTAL.labels(reason="internal_error").inc()
            raise HTTPException(
                status_code=500,
                detail="Emerging threat analysis failed during execution.",
            )

    def get_event(self, event_id_or_fingerprint: str) -> Optional[EmergingThreatEvent]:
        """Retrieves an event by UUID or SHA-256 fingerprint."""
        if event_id_or_fingerprint in self._events_by_id:
            return self._events_by_id[event_id_or_fingerprint]
        if event_id_or_fingerprint in self._fingerprint_to_id:
            e_id = self._fingerprint_to_id[event_id_or_fingerprint]
            return self._events_by_id.get(e_id)
        return None

    def list_events(
        self,
        network_id: Optional[str] = None,
        severity: Optional[str] = None,
        limit: int = 50,
    ) -> List[EmergingThreatEvent]:
        """Lists active early-warning events with optional filters."""
        events = list(self._events_by_id.values())
        if network_id:
            events = [e for e in events if e.network_id == network_id]
        if severity:
            events = [e for e in events if e.severity == severity.upper()]
        # Sort by detected_at descending
        events.sort(key=lambda e: e.detected_at, reverse=True)
        return events[:limit]


# Global singleton instance
emerging_threat_service = EmergingThreatService.get_instance()
