/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AnomaliesRouteImport } from './routes/anomalies'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as GeoTimelineRouteImport } from './routes/geo-timeline'
import { Route as MlIntelligenceRouteImport } from './routes/ml-intelligence'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResearchRouteImport } from './routes/research'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomaliesRoute = AnomaliesRouteImport.update({
  id: '/anomalies',
  path: '/anomalies',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const GeoTimelineRoute = GeoTimelineRouteImport.update({
  id: '/geo-timeline',
  path: '/geo-timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const MlIntelligenceRoute = MlIntelligenceRouteImport.update({
  id: '/ml-intelligence',
  path: '/ml-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anomalies': typeof AnomaliesRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/geo-timeline': typeof GeoTimelineRoute
  '/ml-intelligence': typeof MlIntelligenceRoute
  '/network': typeof NetworkRoute
  '/profiles': typeof ProfilesRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anomalies': typeof AnomaliesRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/geo-timeline': typeof GeoTimelineRoute
  '/ml-intelligence': typeof MlIntelligenceRoute
  '/network': typeof NetworkRoute
  '/profiles': typeof ProfilesRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/anomalies': typeof AnomaliesRoute
  '/assistant': typeof AssistantRoute
  '/audit': typeof AuditRoute
  '/cases': typeof CasesRoute
  '/dashboard': typeof DashboardRoute
  '/evidence': typeof EvidenceRoute
  '/geo-timeline': typeof GeoTimelineRoute
  '/ml-intelligence': typeof MlIntelligenceRoute
  '/network': typeof NetworkRoute
  '/profiles': typeof ProfilesRoute
  '/reports': typeof ReportsRoute
  '/research': typeof ResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/anomalies'
    | '/assistant'
    | '/audit'
    | '/cases'
    | '/dashboard'
    | '/evidence'
    | '/geo-timeline'
    | '/ml-intelligence'
    | '/network'
    | '/profiles'
    | '/reports'
    | '/research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/anomalies'
    | '/assistant'
    | '/audit'
    | '/cases'
    | '/dashboard'
    | '/evidence'
    | '/geo-timeline'
    | '/ml-intelligence'
    | '/network'
    | '/profiles'
    | '/reports'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/anomalies'
    | '/assistant'
    | '/audit'
    | '/cases'
    | '/dashboard'
    | '/evidence'
    | '/geo-timeline'
    | '/ml-intelligence'
    | '/network'
    | '/profiles'
    | '/reports'
    | '/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnomaliesRoute: typeof AnomaliesRoute
  AssistantRoute: typeof AssistantRoute
  AuditRoute: typeof AuditRoute
  CasesRoute: typeof CasesRoute
  DashboardRoute: typeof DashboardRoute
  EvidenceRoute: typeof EvidenceRoute
  GeoTimelineRoute: typeof GeoTimelineRoute
  MlIntelligenceRoute: typeof MlIntelligenceRoute
  NetworkRoute: typeof NetworkRoute
  ProfilesRoute: typeof ProfilesRoute
  ReportsRoute: typeof ReportsRoute
  ResearchRoute: typeof ResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomalies': {
      id: '/anomalies'
      path: '/anomalies'
      fullPath: '/anomalies'
      preLoaderRoute: typeof AnomaliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/geo-timeline': {
      id: '/geo-timeline'
      path: '/geo-timeline'
      fullPath: '/geo-timeline'
      preLoaderRoute: typeof GeoTimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ml-intelligence': {
      id: '/ml-intelligence'
      path: '/ml-intelligence'
      fullPath: '/ml-intelligence'
      preLoaderRoute: typeof MlIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnomaliesRoute: AnomaliesRoute,
  AssistantRoute: AssistantRoute,
  AuditRoute: AuditRoute,
  CasesRoute: CasesRoute,
  DashboardRoute: DashboardRoute,
  EvidenceRoute: EvidenceRoute,
  GeoTimelineRoute: GeoTimelineRoute,
  MlIntelligenceRoute: MlIntelligenceRoute,
  NetworkRoute: NetworkRoute,
  ProfilesRoute: ProfilesRoute,
  ReportsRoute: ReportsRoute,
  ResearchRoute: ResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
