from typing import List
from ..models.entity import Entity, EntityType, EntityMetadata
from ..models.relationship import Relationship, RelationshipType, RelationshipMetadata

INITIAL_ENTITIES: List[Entity] = [
    Entity(
        id="NG-4471",
        name="Raghav Malhotra",
        type=EntityType.PERSON,
        riskScore=94,
        metadata=EntityMetadata(
            alias="Sarpanch",
            role="Kingpin",
            status="At Large",
            network="Ghost Ledger",
            location="Kolkata, Sector 9",
            offenses=["Money laundering", "Arms trafficking", "Extortion"],
            lastSeen="2026-08-21 · Howrah transit hub",
            associates=34,
            position={"x": 50, "y": 46},
            subtitle="Primary subject · Ghost Ledger syndicate lead",
            details=[
                ("Age", "41"),
                ("Status", "At Large"),
                ("Network", "Ghost Ledger"),
                ("Priors", "5 (2 violent)"),
                ("Last seen", "2026-08-21 · Howrah transit hub"),
            ],
        ),
        createdAt="2026-05-02T10:00:00Z",
    ),
    Entity(
        id="NG-4318",
        name="Ayesha Qureshi",
        type=EntityType.PERSON,
        riskScore=88,
        metadata=EntityMetadata(
            alias="Sable",
            role="Financier",
            status="Under Surveillance",
            network="Vault-7 Ring",
            location="Mumbai, Bandra East",
            offenses=["Cyber fraud", "Identity theft"],
            lastSeen="2026-08-24 · Airport terminal 2",
            associates=21,
            position={"x": 24, "y": 24},
            subtitle="Financier · Vault-7 Ring",
            details=[
                ("Role", "Financial controller"),
                ("Status", "Under Surveillance"),
                ("Flagged accounts", "9 offshore"),
            ],
        ),
        createdAt="2026-06-11T12:30:00Z",
    ),
    Entity(
        id="NG-4102",
        name="Vikram Sethi",
        type=EntityType.PERSON,
        riskScore=81,
        metadata=EntityMetadata(
            alias="Nine",
            role="Operative",
            status="In Custody",
            network="Blackwater Cell",
            location="Delhi, Central holding",
            offenses=["Narcotics distribution"],
            lastSeen="2026-08-12 · Custody transfer",
            associates=12,
            position={"x": 78, "y": 26},
            subtitle="Operative · Blackwater Cell",
            details=[
                ("Role", "Distribution handler"),
                ("Status", "In Custody"),
                ("Detention cell", "Block C-4"),
            ],
        ),
        createdAt="2026-06-28T09:15:00Z",
    ),
    Entity(
        id="NG-3990",
        name="Imran Baig",
        type=EntityType.PERSON,
        riskScore=76,
        metadata=EntityMetadata(
            alias="Kestrel",
            role="Courier",
            status="At Large",
            network="Silk Corridor",
            location="Hyderabad, Old City",
            offenses=["Smuggling", "Forgery"],
            lastSeen="2026-08-19 · Border checkpoint 7",
            associates=17,
            position={"x": 80, "y": 70},
            subtitle="Cross-border courier",
            details=[
                ("Role", "Logistics courier"),
                ("Status", "At Large"),
                ("Border crossings", "12 in 90d"),
            ],
        ),
        createdAt="2026-03-19T14:45:00Z",
    ),
    Entity(
        id="ORG-1092",
        name="Zenith Holdings",
        type=EntityType.ORGANIZATION,
        riskScore=71,
        metadata=EntityMetadata(
            role="Shell Entity",
            status="Active",
            network="Ghost Ledger",
            location="Port Louis, Mauritius",
            offenses=["Tax evasion", "Layering"],
            position={"x": 50, "y": 12},
            subtitle="Shell entity · offshore front",
            details=[
                ("Jurisdiction", "Mauritius"),
                ("Beneficial owner", "Undisclosed"),
                ("Linked accounts", "4"),
            ],
        ),
        createdAt="2026-04-10T08:00:00Z",
    ),
    Entity(
        id="ORG-8841",
        name="Meridian Exports",
        type=EntityType.ORGANIZATION,
        riskScore=63,
        metadata=EntityMetadata(
            role="Shell Entity",
            status="Active",
            network="Vault-7 Ring",
            location="Kolkata, Port Trust Area",
            offenses=["Customs fraud"],
            position={"x": 20, "y": 72},
            subtitle="Logistics front",
            details=[
                ("Reg. no", "WB-88210-EXP"),
                ("Suspicious shipments", "14 flagged"),
            ],
        ),
        createdAt="2026-05-15T11:20:00Z",
    ),
    Entity(
        id="PH-9921",
        name="+91 98110 44217",
        type=EntityType.PHONE,
        riskScore=79,
        metadata=EntityMetadata(
            role="Burner Handset",
            status="Active",
            network="Ghost Ledger",
            location="Delhi / Jaipur tower cluster",
            offenses=["Encrypted comms"],
            position={"x": 8, "y": 48},
            subtitle="IMEI 3549 8811 0042",
            details=[
                ("IMEI", "3549 8811 0042"),
                ("Activated", "2026-07-02"),
                ("Unique contacts", "23"),
            ],
        ),
        createdAt="2026-07-02T16:00:00Z",
    ),
    Entity(
        id="BANK-4471",
        name="HDFC Current ****4471",
        type=EntityType.BANK_ACCOUNT,
        riskScore=91,
        metadata=EntityMetadata(
            role="Operating Account",
            status="Flagged",
            network="Ghost Ledger",
            location="New Delhi Branch",
            offenses=["Structured deposits", "Hawala routing"],
            position={"x": 92, "y": 48},
            subtitle="30d Inflow ₹8.4 Cr",
            details=[
                ("Holder", "Meridian Exports"),
                ("30d inflow", "₹8.4 Cr"),
                ("STR filed", "Yes · 2026-08-09"),
            ],
        ),
        createdAt="2026-06-01T09:00:00Z",
    ),
    Entity(
        id="VEH-7742",
        name="DL 3C AY 7742 (Black SUV)",
        type=EntityType.VEHICLE,
        riskScore=63,
        metadata=EntityMetadata(
            role="Transit Vehicle",
            status="Flagged",
            network="Ghost Ledger",
            location="NH-48 Delhi–Jaipur",
            offenses=["ANPR hit watchlist"],
            position={"x": 50, "y": 84},
            subtitle="ANPR Watchlist · 31 corridor hits",
            details=[
                ("Registered to", "Meridian Exports"),
                ("Corridor", "NH-48 Delhi–Jaipur"),
            ],
        ),
        createdAt="2026-06-18T14:10:00Z",
    ),
]

INITIAL_RELATIONSHIPS: List[Relationship] = [
    Relationship(
        id="REL-01",
        sourceId="NG-4471",
        targetId="NG-4318",
        type=RelationshipType.TRANSACTS,
        confidence=0.96,
        metadata=RelationshipMetadata(weight=9, label="funds", detail="₹1.9 Cr routed"),
    ),
    Relationship(
        id="REL-02",
        sourceId="NG-4471",
        targetId="NG-4102",
        type=RelationshipType.ASSOCIATED_WITH,
        confidence=0.91,
        metadata=RelationshipMetadata(weight=7, label="orders", detail="Direct command link"),
    ),
    Relationship(
        id="REL-03",
        sourceId="NG-4471",
        targetId="NG-3990",
        type=RelationshipType.ASSOCIATED_WITH,
        confidence=0.88,
        metadata=RelationshipMetadata(weight=6, label="logistics", detail="Cross-border drops"),
    ),
    Relationship(
        id="REL-04",
        sourceId="NG-4471",
        targetId="ORG-1092",
        type=RelationshipType.ASSOCIATED_WITH,
        confidence=0.94,
        metadata=RelationshipMetadata(weight=8, label="ownership", detail="Beneficial interest"),
    ),
    Relationship(
        id="REL-05",
        sourceId="NG-4318",
        targetId="ORG-8841",
        type=RelationshipType.TRANSACTS,
        confidence=0.89,
        metadata=RelationshipMetadata(weight=5, label="invoices", detail="₹3.2 Cr fictitious billing"),
    ),
    Relationship(
        id="REL-06",
        sourceId="NG-4471",
        targetId="PH-9921",
        type=RelationshipType.CALLS,
        confidence=0.99,
        metadata=RelationshipMetadata(weight=8, label="comms", detail="148 calls in 30d"),
    ),
    Relationship(
        id="REL-07",
        sourceId="ORG-8841",
        targetId="BANK-4471",
        type=RelationshipType.TRANSACTS,
        confidence=0.97,
        metadata=RelationshipMetadata(weight=9, label="banking", detail="Primary operating account"),
    ),
    Relationship(
        id="REL-08",
        sourceId="ORG-8841",
        targetId="VEH-7742",
        type=RelationshipType.ASSOCIATED_WITH,
        confidence=0.95,
        metadata=RelationshipMetadata(weight=4, label="vehicle", detail="Registered corporate vehicle"),
    ),
    Relationship(
        id="REL-09",
        sourceId="NG-3990",
        targetId="VEH-7742",
        type=RelationshipType.LOCATED_AT,
        confidence=0.84,
        metadata=RelationshipMetadata(weight=4, label="transit", detail="Observed driver at checkpoint"),
    ),
    Relationship(
        id="REL-10",
        sourceId="BANK-4471",
        targetId="ORG-1092",
        type=RelationshipType.TRANSACTS,
        confidence=0.92,
        metadata=RelationshipMetadata(weight=8, label="offshore", detail="11 layered transfers"),
    ),
]
